name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify package-lock.json exists
        run: ls -la
        working-directory: ./band-website

      - name: Install dependencies
        run: npm ci
        working-directory: ./band-website

      - name: Inject Production API Key
        run: |
          sed -i "s|'{{GOOGLE_CALENDAR_PROD_API_KEY}}'|'${{ secrets.GOOGLE_CALENDAR_PROD_API_KEY }}'|g" src/environments/environment.prod.ts
        working-directory: ./band-website

      - name: Build Angular app
        run: npm run deploy
        working-directory: ./band-website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'band-website/dist/band-website/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
